monetary_min: 100
monetary_max: 1000000

point_min: 10
point_max: 4000

skill_money_min: 1000
skill_money_max: 1000000

skill_akame_min: 0
skill_akame_max: 3000

attack_and_defense_min: -900
attack_and_defense_max: 900

resist_min: 0
resist_max: 500

remove_default_prices: FALSE
include_coin_lockers: TRUE
include_shops: TRUE
include_wires: TRUE
include_rewards: TRUE