monetary_min: 100
monetary_max: 1000000

point_min: 10
point_max: 4000

skill_money_min: 1000
skill_money_max: 1000000

skill_akame_min: 0
skill_akame_max: 3000

attack_and_defense_min: -200
attack_and_defense_max: 500

resist_min: 0
resist_max: 300

remove_default_prices: TRUE
include_coin_lockers: TRUE
include_shops: TRUE
include_rewards: TRUE
include_pocket_circuit: TRUE
include_minigames: TRUE
include_pool: TRUE
include_golf: TRUE
include_casinos: TRUE
include_shogi: TRUE
include_darts: TRUE
include_consumable_shops: FALSE
include_weird_shops: FALSE