skill_money_min: 1000
skill_money_max: 1000000
skill_akame_min: 0
skill_akame_max: 2000
part_time_money_min: 10000
part_time_money_max: 500000
part_time_akame_min: 0
part_time_akame_max: 2000
attack_and_defense_min: -200
attack_and_defense_max: 500
resist_min: 0
resist_max: 300
enemy_hp_mult: 1.0
enemy_attack_mult: 1.0
randomize_enemy_stats: false
intro_skip: true
seed: null
