monetary_min: 100
monetary_max: 1000000
point_min: 10
point_max: 4000
skill_money_min: 1000
skill_money_max: 1000000
skill_akame_min: 0
skill_akame_max: 3000
attack_and_defense_min: -2000
attack_and_defense_max: 2000
resist_min: 0
resist_max: 400
remove_default_prices: true
include_coin_lockers: false
include_shops: false
include_rewards: true
include_pocket_circuit: true
include_minigames: true
include_pool: true
include_golf: true
include_casinos: true
include_shogi: true
include_darts: true
